export enum ErrorHandlerEvent {
  ERROR_HANDLER_USER = 'ERROR_HANDLER_USER',
  ERROR_HANDLER_SECURITY = 'ERROR_HANDLER_SECURITY',
  ERROR_HANDLER_CONFLICT = 'ERROR_HANDLER_CONFLICT',
  ERROR_HANDLER_UNEXPECTED = 'ERROR_HANDLER_UNEXPECTED'
}
